### ISSUE TITLE
optimization of svg

### ISSUE THREAD

**Issue by fdncred** [ahaoboy/ansi2#10]
I'm wondering if some optimization can be done on the svg to decrease the file size. For instance, I was thinking that maybe, instead of having a tag line for each character, it would be written so that you have a tagline for each word until the color changes.

So, instead of this:
```xml
    <text x="180px" y="16px" width="20px" height="32px" class='green bold'   >
        <tspan>n</tspan>
    </text>
    <text x="200px" y="16px" width="20px" height="32px" class='green bold'   >
        <tspan>a</tspan>
    </text>
    <text x="220px" y="16px" width="20px" height="32px" class='green bold'   >
        <tspan>m</tspan>
    </text>
    <text x="240px" y="16px" width="20px" height="32px" class='green bold'   >
        <tspan>e</tspan>
    </text>
```
It could be something like this:
```xml
    <text x="180px" y="16px" width="20px" height="32px" class='green bold'   >
        <tspan>name</tspan>
    </text>

```
I know literally nothing about writing svg files so it may not be possible. I was just looking for a way to make the file size smaller.

**Comment by fdncred** [comment]
Another thought for minifying it would be to only keep the style colors that are actually in use in the svg, if that's possible.

**Comment by ahaoboy** [comment]
I am not familiar with CSS. The reason why each character has a text tag is that if the characters like 111 are combined, the width will become smaller. This may be related to the font or some CSS properties.

If you use the -c option, it will be minified using svgo, which should remove unused css

I am also looking for how to optimize the size, maybe I need to ask chatgpt for help to learn some CSS knowledge
