### ISSUE TITLE
256 color index lookups with 38;5 and 48;5

### ISSUE THREAD

**Issue by fdncred** [ahaoboy/ansi2#4]
It would be great to also support 256 color index colors.
https://en.wikipedia.org/wiki/ANSI_escape_code#8-bit

**Comment by ahaoboy** [comment]
This shouldn't be hard, can you give me an example? Or which tools will generate 256 color ansi?

**Comment by fdncred** [comment]
The attached file is the output from nushell, which uses the [lscolors crate](https://crates.io/crates/lscolors) to color the name column in the `ls` output.
[table.txt](https://github.com/user-attachments/files/17395090/table.txt)

This is what it looks like in my terminal
![image](https://github.com/user-attachments/assets/213bc2eb-be29-49c4-bdba-5be29132bda5)

You'll also note that it uses ansi hyperlinks, which would be another interesting thing to support with your crate. Thanks!

**Comment by ahaoboy** [comment]
This is very interesting, but adding links to svg is a bit troublesome. Currently, it can only display content, and the bar cannot be clicked. Maybe some optimization is needed.


![table](https://github.com/user-attachments/assets/d64dad88-b754-4fa7-a311-bd7909f382e4)

**Comment by ahaoboy** [comment]
In order to display the font correctly, you also need to add the font parameter and specify a mono font, otherwise the characters may be offset.
```
 cat ./assets/table.ans | cr --features=cli -- -f=svg -m=dark -t=ubuntu --font=C:/tool/FiraCode/FiraCodeNerdFontMono-Regular.ttf > table.svg
```

**Comment by fdncred** [comment]
> This is very interesting, but adding links to svg is a bit troublesome. Currently, it can only display content, and the bar cannot be clicked. Maybe some optimization is needed.
> 


I'm totally fine with just ignoring the hyperlinks for now. My problem was that it was drawing the hyperlinks in a test I did and that messed up the table representation.

**Comment by fdncred** [comment]
btw - the README.md in your screenshot is colored wrong. Note the difference between my screenshot and yours. Mine has black text on a yellow-ish background, yours has yellow-ish text on a black background.

**Comment by ahaoboy** [comment]
![image](https://github.com/user-attachments/assets/6ea2fc8e-03e9-4b29-8121-0d280f287a29)

The difference in color is due to different color schemes, such as vscode, xterm, Ubuntu, vga, etc. Different color schemes are slightly different, and ansi2 will output html and svg that support dark mode, so in dark mode it will only invert pure black and white and gray. You can also use --mode=light to disable this function.

**Comment by fdncred** [comment]
ok, I guess I thought it was looking at the terminal's theme versus using one of the built-in ones. I'll try your PR in a little while but thank you so much for working on it! I appreciate all you've done.

**Comment by ahaoboy** [comment]
> The attached file is the output from nushell, which uses the [lscolors crate](https://crates.io/crates/lscolors) to color the name column in the `ls` output

How do I save the output of nushell to a file? I tried using redirection but it doesn't work 
```
ls o> a.ans
```
![image](https://github.com/user-attachments/assets/3d790ca0-64fe-42b4-842a-49a8023de70d)

**Comment by fdncred** [comment]
`ls | table o> a.ans` is what I use. `table` forces output to be turned into strings whereas `ls blah` works with structured data so you can do `ls | where size > 10kb`. Sometimes you may want to add -e like `$nu | table -e o> b.ans` because the data is nested. Then you can do `open a.ans` or `open b.ans` and that re-renders it to the screen.
